add damage parameters for tropical cyclone damage function
pik-piam/mrremind pull request #259
Opened 2022-05-09 15:40 UTC by fpiontek

This adds the data in TCdamageKrichene to the REMIND input data. There are two subtypes for two damage parameters.

2022-05-09 16:36 UTC, LaviniaBaumstark reviewed
looks good, please ensure that the checks do not fail

2022-05-09 18:40 UTC, fpiontek commented on R/convertTCdamage.R
> +	out <- toolCountryFill(x,fill=0,verbosity=3)
I changed that and fixed the typo which caused the check to fail.

2022-05-10 07:14 UTC, LaviniaBaumstark requested changes

2022-05-10 07:14 UTC, LaviniaBaumstark commented on R/calcTCdamage.R
> +
you have to document the subtype here

2022-05-11 16:55 UTC, fpiontek commented on R/calcTCdamage.R
> +
done

2022-05-11 20:42 UTC, LaviniaBaumstark approved these changes

2022-05-12 05:24 UTC, merged