Add Historical Industry Value Added Figures to historical.mif
pik-piam/mrremind pull request #396
Opened 2023-05-12 12:38 UTC by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q

Test runs pending …

2023-05-12 13:39 UTC, fbenke-pik commented
Not sure if putting read and convert into one file is a problem (UNIDO.R as opposed to creating two files readUNIDO.R and convertUNIDO.R) @LaviniaBaumstark can you comment on this?

2023-05-15 06:49 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
No unexpected differences in output.
```
$ diff -I '^\*' -q rev6.52_62eff8f7_remind/ rev6.52-test-UNIDO_62eff8f7_remind/ | column -t
Files  rev6.52_62eff8f7_remind/config.rds       and  rev6.52-test-UNIDO_62eff8f7_remind/config.rds       differ
Files  rev6.52_62eff8f7_remind/diagnostics.log  and  rev6.52-test-UNIDO_62eff8f7_remind/diagnostics.log  differ
Files  rev6.52_62eff8f7_remind/pucFiles         and  rev6.52-test-UNIDO_62eff8f7_remind/pucFiles         differ

$ diff -I '^\*' -q rev6.52_62eff8f7_validationremind/ rev6.52-test-UNIDO_62eff8f7_validationremind/ | column -t
Files  rev6.52_62eff8f7_validationremind/config.rds       and  rev6.52-test-UNIDO_62eff8f7_validationremind/config.rds       differ
Files  rev6.52_62eff8f7_validationremind/diagnostics.log  and  rev6.52-test-UNIDO_62eff8f7_validationremind/diagnostics.log  differ
Files  rev6.52_62eff8f7_validationremind/historical.mif   and  rev6.52-test-UNIDO_62eff8f7_validationremind/historical.mif   differ
Files  rev6.52_62eff8f7_validationremind/pucFiles         and  rev6.52-test-UNIDO_62eff8f7_validationremind/pucFiles         differ

$ diff rev6.52_62eff8f7_validationremind/historical.mif rev6.52-test-UNIDO_62eff8f7_validationremind/historical.mif | cut -c -80
10576a10577,10628
> INDSTAT2;historical;CAZ;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;CHA;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;EUR;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;IND;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;JPN;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;LAM;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;MEA;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;NEU;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;OAS;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;REF;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;SSA;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;USA;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;World;cement;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;CAZ;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;CHA;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;EUR;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;IND;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;JPN;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;LAM;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;MEA;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;NEU;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;OAS;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;REF;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;SSA;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;USA;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;World;chemicals;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/
> INDSTAT2;historical;CAZ;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;CHA;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;EUR;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;IND;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;JPN;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;LAM;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;MEA;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;NEU;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;OAS;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;REF;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;SSA;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;USA;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N
> INDSTAT2;historical;World;otherInd;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
> INDSTAT2;historical;CAZ;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;CHA;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;EUR;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;IND;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;JPN;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;LAM;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;MEA;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;NEU;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;OAS;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;REF;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;SSA;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;USA;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;
> INDSTAT2;historical;World;steel;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/
```

2023-05-15 09:01 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> please, split UNIDO.R into readUNIDO.R and ConvertUNIDO.R, otherwise some functionality of madrat functions will get lost

1. Which madrat functionality would that be, that magically infers information about functions from files it has no access to?
2. What are the special techniques used in these 128 examples that make this wonderous mardrat functionality work, so I can use it here as well?
   [mrcommons/R/calcGDPppp.R: calcGDPppp](https://github.com/pik-piam/mrcommons/blob/master/R/calcGDPppp.R#L17)
   [mrcommons/R/calcGDPppp.R: calcGDPpppFuture](https://github.com/pik-piam/mrcommons/blob/master/R/calcGDPppp.R#L36)
   [mrcommons/R/calcGDPppp.R: calcGDPpppPast](https://github.com/pik-piam/mrcommons/blob/master/R/calcGDPppp.R#L50)
   [mrcommons/R/convertEurostat.R: convertEurostat](https://github.com/pik-piam/mrcommons/blob/master/R/convertEurostat.R#L13)
   [mrcommons/R/convertEurostat.R: convertEurostatSectorEmi](https://github.com/pik-piam/mrcommons/blob/master/R/convertEurostat.R#L25)
   [mrcommons/R/convertEurostat.R: convertEurostatMACCemi](https://github.com/pik-piam/mrcommons/blob/master/R/convertEurostat.R#L62)
   [mrcommons/R/readEurostat.R: readEurostat](https://github.com/pik-piam/mrcommons/blob/master/R/readEurostat.R#L19)
   [mrcommons/R/readEurostat.R: readEurostatEmissions](https://github.com/pik-piam/mrcommons/blob/master/R/readEurostat.R#L32)
   [mrcommons/R/readGGCMICropCalendar.R: readGGCMICropCalendar](https://github.com/pik-piam/mrcommons/blob/master/R/readGGCMICropCalendar.R#L14)
   [mrcommons/R/readGGCMICropCalendar.R: toolReadArea](https://github.com/pik-piam/mrcommons/blob/master/R/readGGCMICropCalendar.R#L47)
   [mrcommons/R/readGGCMICropCalendar.R: toolReadCal](https://github.com/pik-piam/mrcommons/blob/master/R/readGGCMICropCalendar.R#L89)
   [mrdrivers/R/calcDriver.R: calcDriver](https://github.com/pik-piam/mrdrivers/blob/master/R/calcDriver.R#L54)
   [mrdrivers/R/calcDriver.R: calcScenarioConstructor](https://github.com/pik-piam/mrdrivers/blob/master/R/calcDriver.R#L101)
   [mrdrivers/R/calcDriver.R: calcHarmonizedData](https://github.com/pik-piam/mrdrivers/blob/master/R/calcDriver.R#L152)
   [mrdrivers/R/calcDriver.R: calcPastData](https://github.com/pik-piam/mrdrivers/blob/master/R/calcDriver.R#L185)
   [mrdrivers/R/calcDriver.R: calcFutureData](https://github.com/pik-piam/mrdrivers/blob/master/R/calcDriver.R#L219)
   [mrdrivers/R/calcGDPFuture.R: calcGDPFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L12)
   [mrdrivers/R/calcGDPFuture.R: calcInternalGDPFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L26)
   [mrdrivers/R/calcGDPFuture.R: calcInternalGDPFutureSSPs](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L46)
   [mrdrivers/R/calcGDPFuture.R: calcInternalGDPFutureSDPs](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L120)
   [mrdrivers/R/calcGDPFuture.R: calcInternalGDPFutureSSP2EU](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L130)
   [mrdrivers/R/calcGDPFuture.R: calcInternalGDPMI](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPFuture.R#L149)
   [mrdrivers/R/calcGDPHarmonized.R: calcGDPHarmonized](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPHarmonized.R#L6)
   [mrdrivers/R/calcGDPHarmonized.R: toolMultiplyGDPpcWithPop](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPHarmonized.R#L20)
   [mrdrivers/R/calcGDPHarmonized.R: toolGDPHarmonizeSSP2EU](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPHarmonized.R#L36)
   [mrdrivers/R/calcGDPPast.R: calcGDPPast](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L27)
   [mrdrivers/R/calcGDPPast.R: calcInternalGDPPast](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L40)
   [mrdrivers/R/calcGDPPast.R: calcInternalGDPPastWDI](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L69)
   [mrdrivers/R/calcGDPPast.R: calcInternalGDPPastEurostat](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L80)
   [mrdrivers/R/calcGDPPast.R: calcInternalGDPPastJames](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L95)
   [mrdrivers/R/calcGDPPast.R: fillWithWBFromJames2019](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L108)
   [mrdrivers/R/calcGDPPast.R: calcInternalGDPPastPWT](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPPast.R#L142)
   [mrdrivers/R/calcGDPpcFuture.R: calcGDPpcFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcFuture.R#L10)
   [mrdrivers/R/calcGDPpcFuture.R: toolGDPpcFutureSSPsOld](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcFuture.R#L34)
   [mrdrivers/R/calcGDPpcFuture.R: toolGDPpcFutureSDPs](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcFuture.R#L50)
   [mrdrivers/R/calcGDPpcFuture.R: toolGDPpcMI](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcFuture.R#L58)
   [mrdrivers/R/calcGDPpcHarmonized.R: calcGDPpcHarmonized](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L7)
   [mrdrivers/R/calcGDPpcHarmonized.R: toolGDPpcHarmonizeSSP](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L26)
   [mrdrivers/R/calcGDPpcHarmonized.R: toolGDPpcHarmonizeSDP](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L91)
   [mrdrivers/R/calcGDPpcHarmonized.R: toolDivideGDPbyPop](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L117)
   [mrdrivers/R/calcGDPpcHarmonized.R: toolGDPpcHarmonizeShortCovid](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L138)
   [mrdrivers/R/calcGDPpcHarmonized.R: toolGDPpcHarmonizeLongCovid](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L164)
   [mrdrivers/R/calcGDPpcHarmonized.R: convergeSpecial](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L196)
   [mrdrivers/R/calcGDPpcHarmonized.R: computeSHAPEgrowth](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L283)
   [mrdrivers/R/calcGDPpcHarmonized.R: logisticTransition](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcHarmonized.R#L351)
   [mrdrivers/R/calcGDPpcPast.R: calcGDPpcPast](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcPast.R#L9)
   [mrdrivers/R/calcGDPpcPast.R: cGDPpcFromGDPAndPop](https://github.com/pik-piam/mrdrivers/blob/master/R/calcGDPpcPast.R#L24)
   [mrdrivers/R/calcLabourFuture.R: calcLabourFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L7)
   [mrdrivers/R/calcLabourFuture.R: calcInternalLabourFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L17)
   [mrdrivers/R/calcLabourFuture.R: calcInternalLabourFutureSSPs](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L42)
   [mrdrivers/R/calcLabourFuture.R: calcInternalLabourFutureSDPs](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L58)
   [mrdrivers/R/calcLabourFuture.R: calcInternalLabourFutureSSP2EU](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L67)
   [mrdrivers/R/calcLabourFuture.R: calcInternalLabourFutureSSPsOld](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourFuture.R#L91)
   [mrdrivers/R/calcLabourPast.R: calcLabourPast](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourPast.R#L7)
   [mrdrivers/R/calcLabourPast.R: calcInternalLabourPast](https://github.com/pik-piam/mrdrivers/blob/master/R/calcLabourPast.R#L17)
   [mrdrivers/R/calcPopulationFuture.R: calcPopulationFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcPopulationFuture.R#L13)
   [mrdrivers/R/calcPopulationFuture.R: calcInternalPopulationFuture](https://github.com/pik-piam/mrdrivers/blob/master/R/calcPopulationFuture.R#L26)
   [mrdrivers/R/calcPopulationFuture.R: calcInternalPopulationFutureSSPs](https://github.com/pik-piam/mrdrivers/blob/maste [...]

2023-05-15 09:09 UTC, LaviniaBaumstark commented
Also if most of the functionality also works for your version, the rule is different and all madrat function rely on this. I cannot guarantee (and also not test) that all madrat functionality is working for your version. If everyone follows the rules, clear interfaces are provided. In addition, following the rules enables other developer to understand your code easier.

2023-05-15 09:22 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> Also if most of the functionality also works for your version, the rule is different and all madrat function rely on this. I cannot guarantee (and also not test) that all madrat functionality is working for your version. If everyone follows the rules, clear interfaces are provided. In addition, following the rules enables other developer to understand your code easier.

There is no functionality in madrat that depends on either the name of source code files, or the number of functions defined inside source code files.  There can't be, because that information is simply not available to the madrat package.

2023-05-15 10:21 UTC, LaviniaBaumstark commented
why do you want to make it different?

2023-05-15 12:16 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
Because `readUNIDO()`, `convertUNIDO()`, `calcUNIDO()` are a logical unit.  Working on any of those functions is easier when one has an understanding what the preceding function does.  Thus it is helpful to have them in one file.

2023-05-15 13:07 UTC, fbenke-pik commented
We checked back with the rest of the RSE group. Michaja, you are right, there is no technical requirement to write separate functions. 

Splitting read and convert into functions with the same name ist recommended way to do it, but not a convention we enforce. We recommend it as a convention, because it helps newcomers with finding specific functionality fast and getting a quick overview of what the R functions of an mr package do.

2023-05-15 13:16 UTC, fbenke-pik requested changes

2023-05-15 13:16 UTC, fbenke-pik commented on R/calcHistorical.R
> +  industry_VA <- calcOutput(type = 'UNIDO', subtype = 'INDSTAT2',
Please no longer add new functionality to calcHistorical, but call the calc function directly in fullVALIDATIONREMIND. 

(`calcHistorical` is legacy code and will be split up in the long run. Creating an input data revision is done using the retrieveData wrapper calling `full...` functions)

2023-05-15 14:22 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> We recommend it as a convention, because it helps newcomers with finding specific functionality fast and getting a quick overview of what the R functions of an mr package do.

Not sure whether "finding specific functionality fast" is the right term for scrolling through a list of 267 files whose names start all with one of three words …
Honestly, teach newcomers to search for code instead.

2023-05-15 15:52 UTC, fbenke-pik approved these changes

2023-05-16 07:59 UTC, LaviniaBaumstark approved these changes

2023-05-16 09:19 UTC, merged