Add trajectories for incineration rates for plastic waste
pik-piam/mrremind pull request #449
Opened 2023-11-21 17:01 UTC by mellamoSimon

Adds required functions and a mapping to create an input file with incineration rates for plastic waste, using data from PBL's Steggman et.al.

2023-11-22 09:06 UTC, fbenke-pik requested changes
Please make sure lucode2::buildLibrary() succeeds and the version is incremented. This should also include fixing remaining linter warnings.

2023-11-23 08:34 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
```diff
       units = "fraction", only.new = TRUE
       ) %>%
       # remove unused dimensions
-    select(c(-model,-scenario,-variable,-unit)) %>%
+    select(-'model', -'scenario',-'variable', -'unit') %>%
     interpolate_missing_periods(seq(2050,2060,5),method = "linear")
 
   # as magpie
```

2023-11-23 10:52 UTC, mellamoSimon commented
thank you!

2023-11-23 10:55 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2023-11-23 11:23 UTC, fbenke-pik approved these changes

2023-11-23 11:40 UTC, merged